version: '3'
services:

  node-app:
    build: 
      context: .
      target: development
    volumes: 
      - ./src:/app/src:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    ports:
      - "27018:27017"

  redis:
    image: redis
      
volumes:
  mongo-db:
